version: "3.9"

services:     
  mishka_cms:
    image: mishak_app:latest
    container_name: mishka_cms
    restart: always
    working_dir: /app
    hostname: mishka_cms
    networks:
      netowrk:
    ports:
      - "4000:4000" # for web
      - "4001:4001" # for api
    environment:
      - DATABASE_USER=mishka_user
      - DATABASE_PASSWORD=mishka_password
      - DATABASE_HOST=mishka_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mishka_database
    volumes:
      - cms:/app/Mnesia.nonode@nohost
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mishka_db
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
      
      
  mishka_db:
    image: mishkagroup/postgresql:3.14
    container_name: mishka_db
    hostname: mishka_db
    restart: always
    networks:
      netowrk:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_USER=mishka_user
      - DATABASE_PASSWORD=mishka_password
      - DATABASE_NAME=mishka_database
    volumes:
      - database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "300m"


networks:
  netowrk:

volumes:
  cms:
  database:
