name: MishkaCms CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    strategy:
      matrix:
        otp: ['24.x']
        elixir: ['1.13.2']
        postgres: ['13.5-alpine']

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: mishka_database_repo
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
        
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1.10.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Elixir and Erlang Dependencies
        run: | 
          mix local.hex --force
          mix local.rebar --force
          mix archive.install hex phx_new --force
      - name: Source Compiling
        run: | 
          mix deps.get
          mix deps.compile
          mix assets.deploy
      - name: Database Dependencies
        env:
          DATABASE_NAME: mishka_database_repo
          DATABASE_USER: mishka_database_repo
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: | 
          mix ecto.create
          mix ecto.migrate
      - name: Run tests
        env:
          SECRET_KEY_BASE_API: qP5c9diga3k115/empFNEEi/fgwXkhArZvpvFaiLqdi3Um1ntPh0P2AkleLzEpzY
          SECRET_KEY_BASE_HTML: afY0EvH0QD34GEhkEiXGjDAnxp9lskQjRbMQ1K8v69t3ZzPCK8RU+rbD4K3E3yHa
          LIVE_VIEW_SALT: wqSr52l4
          TOKEN_JWT_KEY: Exe6Qk6YPWWNmOS7rAtXQfPPngruPtEIivDB1nsXwSk
          SECRET_CURRENT_TOKEN_SALT: TestSaltCurrentToken
          SECRET_REFRESH_TOKEN_SALT: TestRefreshSaltToken
          SECRET_ACCESS_TOKEN_SALT: TestAccessSaltToken
          EMAIL_SYSTEM: test@test.com
          EMAIL_DOMAIN: test.com
          EMAIL_PORT: '587'
          EMAIL_SERVER: test.test.com
          EMAIL_HOSTNAME: test.test.org
          EMAIL_USERNAME: test@test.com
          EMAIL_PASSWORD: TestPasswordForEmail
        run: mix test